{
  "variables": {
    "type": "object",
    "properties": {
      "env": {
        "type": "object",
        "title": "Environment Variables",
        "description": "Environment variables to set when starting a flow run.",
        "additionalProperties": {
          "type": "string"
        }
      },
      "name": {
        "type": "string",
        "title": "Name",
        "description": "Name given to infrastructure created by a worker."
      },
      "image": {
        "type": "string",
        "title": "Image",
        "example": "docker.io/prefecthq/prefect:2-latest",
        "description": "The image reference of a container image to use for created jobs. If not set, the latest Prefect image will be used."
      },
      "labels": {
        "type": "object",
        "title": "Labels",
        "description": "Labels applied to infrastructure created by a worker.",
        "additionalProperties": {
          "type": "string"
        }
      },
      "command": {
        "type": "string",
        "title": "Command",
        "description": "The command to use when starting a flow run. In most cases, this should be left blank and the command will be automatically generated by the worker."
      },
      "affinity": {
        "type": "object",
        "title": "Affinity",
        "default": {},
        "properties": {
          "podAffinity": {
            "type": "object",
            "description": "Pod affinity rules for scheduling."
          },
          "nodeAffinity": {
            "type": "object",
            "description": "Node affinity rules for scheduling."
          },
          "podAntiAffinity": {
            "type": "object",
            "description": "Pod anti-affinity rules for scheduling."
          }
        },
        "description": "Specify pod affinity and anti-affinity rules."
      },
      "namespace": {
        "type": "string",
        "title": "Namespace",
        "default": "prefect",
        "description": "The Kubernetes namespace to create jobs within."
      },
      "resources": {
        "type": "object",
        "title": "Resources",
        "required": [
          "requests",
          "limits"
        ],
        "properties": {
          "limits": {
            "type": "object",
            "title": "Resource Limits",
            "required": [
              "memory",
              "cpu"
            ],
            "properties": {
              "cpu": {
                "type": "string",
                "title": "CPU Limit",
                "default": "0.5",
                "description": "The maximum amount of CPU allowed for the job."
              },
              "memory": {
                "type": "string",
                "title": "Memory Limit",
                "example": "500Mi",
                "description": "The maximum amount of memory allowed for the job."
              }
            },
            "description": "The maximum amount of resources allowed for the job."
          },
          "requests": {
            "type": "object",
            "title": "Resource Requests",
            "required": [
              "memory",
              "cpu"
            ],
            "properties": {
              "cpu": {
                "type": "string",
                "title": "CPU Request",
                "default": "0.5",
                "description": "The amount of CPU requested for the job."
              },
              "memory": {
                "type": "string",
                "title": "Memory Request",
                "default": "500Mi",
                "description": "The amount of memory requested for the job."
              }
            },
            "description": "The minimum amount of resources required for the job."
          }
        },
        "description": "The resource requests and limits for the Kubernetes job."
      },
      "tolerations": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string"
            },
            "value": {
              "type": "string"
            },
            "effect": {
              "type": "string"
            },
            "operator": {
              "type": "string"
            },
            "tolerationSeconds": {
              "type": "integer"
            }
          }
        },
        "title": "Tolerations",
        "description": "Specify tolerations for pods."
      },
      "stream_output": {
        "type": "boolean",
        "title": "Stream Output",
        "default": true,
        "description": "If set, output will be streamed from the job to local standard output."
      },
      "cluster_config": {
        "allOf": [
          {
            "$ref": "#/definitions/KubernetesClusterConfig"
          }
        ],
        "title": "Cluster Config",
        "description": "The Kubernetes cluster config to use for job creation."
      },
      "finished_job_ttl": {
        "type": "integer",
        "title": "Finished Job TTL",
        "description": "The number of seconds to retain jobs after completion. If set, finished jobs will be cleaned up by Kubernetes after the given delay. If not set, jobs will be retained indefinitely."
      },
      "image_pull_policy": {
        "enum": [
          "IfNotPresent",
          "Always",
          "Never"
        ],
        "type": "string",
        "title": "Image Pull Policy",
        "default": "IfNotPresent",
        "description": "The Kubernetes image pull policy to use for job containers."
      },
      "service_account_name": {
        "type": "string",
        "title": "Service Account Name",
        "description": "The Kubernetes service account to use for job creation."
      },
      "job_watch_timeout_seconds": {
        "type": "integer",
        "title": "Job Watch Timeout Seconds",
        "default": 600,
        "description": "Number of seconds to wait for each event emitted by a job before timing out. If not set, the worker will wait for each event indefinitely."
      },
      "pod_watch_timeout_seconds": {
        "type": "integer",
        "title": "Pod Watch Timeout Seconds",
        "default": 600,
        "description": "Number of seconds to watch for pod creation before timing out."
      }
    },
    "definitions": {
      "KubernetesClusterConfig": {
        "type": "object",
        "title": "KubernetesClusterConfig",
        "required": [
          "config",
          "context_name"
        ],
        "properties": {
          "config": {
            "type": "object",
            "title": "Config",
            "description": "The entire contents of a kubectl config file."
          },
          "context_name": {
            "type": "string",
            "title": "Context Name",
            "description": "The name of the kubectl context to use."
          }
        },
        "description": "Stores configuration for interaction with Kubernetes clusters.\n\nSee `from_file` for creation.",
        "secret_fields": [],
        "block_type_slug": "kubernetes-cluster-config",
        "block_schema_references": {}
      }
    },
    "description": "Default variables for the Kubernetes worker.\n\nThe schema for this class is used to populate the `variables` section of the default\nbase job template."
  },
  "job_configuration": {
    "env": "{{ env }}",
    "name": "{{ name }}",
    "labels": "{{ labels }}",
    "command": "{{ command }}",
    "namespace": "{{ namespace }}",
    "job_manifest": {
      "kind": "Job",
      "spec": {
        "template": {
          "spec": {
            "affinity": "{{ affinity }}",
            "containers": [
              {
                "env": "{{ env }}",
                "args": "{{ command }}",
                "name": "prefect-job",
                "image": "{{ image }}",
                "resources": "{{ resources }}",
                "imagePullPolicy": "{{ image_pull_policy }}"
              }
            ],
            "completions": 1,
            "parallelism": 1,
            "tolerations": "{{ tolerations }}",
            "restartPolicy": "Never",
            "serviceAccountName": "{{ service_account_name }}"
          }
        },
        "backoffLimit": 0,
        "ttlSecondsAfterFinished": "{{ finished_job_ttl }}"
      },
      "metadata": {
        "labels": "{{ labels }}",
        "namespace": "{{ namespace }}",
        "generateName": "{{ name }}-"
      },
      "apiVersion": "batch/v1"
    },
    "stream_output": "{{ stream_output }}",
    "cluster_config": "{{ cluster_config }}",
    "job_watch_timeout_seconds": "{{ job_watch_timeout_seconds }}",
    "pod_watch_timeout_seconds": "{{ pod_watch_timeout_seconds }}"
  }
}