fullnameOverride: prefect-worker-test
worker:
  livenessProbe:
    enabled: true
  apiConfig: server
  config:
    workPool: "test"
  serverApiConfig:
    apiUrl: "http://prefect-server.prefect.svc.cluster.local.:4200/api"
  replicaCount: 1
  resources:
    limits:
      cpu: "250m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "512Mi"
  image:
    repository: "dockerhub.timeweb.cloud/prefecthq/prefect"
    prefectTag: "2.20.13-python3.10-kubernetes"
