---
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name:
  namespace:
spec:
  type: Python
  pythonVersion: '3'
  mode: cluster
  image: cr.yandex/crp7mhgrb3nvmpj6fbfo/k8s-spark-image/python-3.10.14:latest
  imagePullPolicy: Always
  mainApplicationFile: ''
  sparkVersion: 3.5.1
  sparkConf:
    spark.driver.extraJavaOptions: -Dlog4j.configuration=file:/opt/spark/log4j.properties
    spark.executor.extraJavaOptions: -Dlog4j.configuration=file:/opt/spark/log4j.properties
  driver:
    cores: 1
    memory: 512m
    labels:
      version: 3.5.1
    serviceAccount: sparkoperator-service-account
    tolerations:
      - key: role
        operator: Equal
        value: spark-app
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: role
                  operator: In
                  values: [spark-app]
  executor:
    cores: 1
    instances: 1
    memory: 512m
    labels:
      version: 3.5.1
    serviceAccount: spark-service-account
    tolerations:
      - key: role
        operator: Equal
        value: spark-app
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: role
                  operator: In
                  values: [spark-app]
  deps:
    files: [local:///opt/spark/log4j.properties]
